# Generated by Django 5.1.1 on 2024-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Char1DMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(db_index=True, max_length=64)),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField()),
                ("count", models.IntegerField()),
            ],
            options={
                "db_table": "marketrunner_chart_1d_market_data",
            },
        ),
        migrations.CreateModel(
            name="Chart1DForecastTimeGPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.CharField(max_length=64)),
                ("to_date", models.CharField(max_length=64)),
                ("dates", models.TextField(null=True)),
                ("values", models.TextField(null=True)),
                ("high_90s", models.TextField(null=True)),
                ("low_90s", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "marketrunner_chart_1d_forecast_time_gpt",
                "indexes": [
                    models.Index(
                        fields=["from_date", "to_date"],
                        name="marketrunne_from_da_95b7ec_idx",
                    )
                ],
            },
        ),
    ]
