# Generated by Django 4.2.16 on 2024-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chart1DForecastTimeGPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.CharField(max_length=256)),
                ("to_date", models.CharField(max_length=256)),
                ("dates", models.TextField(null=True)),
                ("values", models.TextField(null=True)),
                ("high_90s", models.TextField(null=True)),
                ("low_90s", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("from_date", "to_date")},
            },
        ),
    ]
