# Generated by Django 5.1.1 on 2024-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="char1dmarketdata",
            name="count",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="char1dmarketdata",
            name="volume",
            field=models.FloatField(default=None, null=True),
        ),
    ]
