# Generated by Django 4.2.16 on 2024-10-06 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chart1dforecasttimegpt",
            table="chart_1d_forecast_time_gpt",
        ),
    ]
