# Generated by Django 5.1.1 on 2024-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_char1dmarketdata_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart1dforecasttimegpt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
