# Generated by Django 4.2.16 on 2024-10-06 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_chart1dforecasttimegpt_table"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chart1dforecasttimegpt",
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="chart1dforecasttimegpt",
            index_together={("from_date", "to_date")},
        ),
    ]
